### ISSUE TITLE
issue building docker continer for R example

### ISSUE THREAD

**Issue by slwu89** [sdwfrost/model-runner-zoo#1]
Hi @sdwfrost, when building the R docker container using `docker-compose build run-model` it has some problems installing the jsonvalidate package and the V8 package it depends on (error below). I tried building the docker container with the most recent version of the r-base image as well as 4.1.3 in the dockerfile; I also tried changing the date of the CRAN snapshot in install.R to a more recent snapshot and still had the same issues. Do you happen to have any idea what's going on? It's a bit confusing as I didn't encounter this issue when building the first version of the connector in May.

```
Warning messages:
1: In install.packages(pkgs, dependencies = TRUE, clean = TRUE, repos = "https://cran.microsoft.com/snapshot/2022-03-30") :
  installation of package ‘V8’ had non-zero exit status
2: In install.packages(pkgs, dependencies = TRUE, clean = TRUE, repos = "https://cran.microsoft.com/snapshot/2022-03-30") :
  installation of package ‘jsonvalidate’ had non-zero exit status
```

**Comment by sdwfrost** [comment]
Hi @slwu89 - I can't reproduce this. It builds just fine on my Windows box with a fresh clone.
